spring.application.name=anbatocom
spring.datasource.url=jdbc:mysql://localhost:3306/
spring.datasource.username=root
spring.datasource.password=Viethau2003.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#port
server.port=8090